name = "front-chat"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/front-chat/./target/wasm32-unknown-unknown/release/front_chat.wasm"
description = "A basic HTTP server built with Theater WebAssembly actors"

[[handler]]
type = "runtime"

[[handler]]
type = "http-framework"

[[handler]]
type = "supervisor"

[[handler]]
type = "random"

[[handler]]
type = "message-server"
