name = "front-chat"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/front-chat/./target/wasm32-unknown-unknown/release/front_chat.wasm"
description = "A basic HTTP server built with Theater WebAssembly actors"
init_state = "/Users/colinrozzi/work/actor-registry/front-chat/configs/moonshot.json"

[[handler]]
type = "runtime"

[[handler]]
type = "http-framework"

[[handler]]
type = "supervisor"

[[handler]]
type = "random"
max_bytes = 1048576
max_int = 9223372036854775807
allow_crypto_secure = false

[[handler]]
type = "message-server"
